### ISSUE TITLE
Автогенерация Qt проектов

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#11]
У вас сейчас QMake используется только, если в проекте есть *.pro файл. 

Большинство студентов делают свои работы в студии, у них *.pro отсутствуют.

Для генерации в таком случае надо использовать: qmake -project, и проверять сборку КАЖДОГО проекта. Потому что неизвестно, какое задание использует Qt, а какое - нет.

Стоит потом дописывать в сгенерированный файл строки

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

Чтобы она 100% компилилась.

**Comment by boral660** [comment]
Реализовал. Так же теперь можно указать опцию main_builder (см. readme);
По умолчанию собирается сначала создаются .pro, затем пытается собрать qmake, если нет, cmake.
Проверил на проектах, которые мне кидали, компилируются удачно.

[UPD] Нашлись существенные ошибки при выборе сборщика

**Comment by boral660** [comment]
Исправил ошибки, и протестировал на некоторых работах.
