### ISSUE TITLE
Проблемы с файлами, в имени которых есть пробелы.

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#12]
CMake выдаёт что-то такое:

CMake Error at CMakeLists.txt:3 (add_executable):

```
  Cannot find source file:



    ../OP



  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: main
```

Но имя файла всего на всего: OP Lab1 Code.cpp

Надо починить.

Заодно проверьте, что будет если в имени файла будут русские буквы.

**Comment by boral660** [comment]
С пробелами ошибку разобрался как исправить, а вот русскими буквами нет. cmake не может работать с кириллицей.
Мне рекурсивно обходить и переименновывать все файлы с кириллицей которые найду? Или выдавать какое-то сообщение?

**Comment by mamontov-cpp** [comment]
Да, я думаю, лучше рекурсивно переименовать.
Переименуйте заодно и папки тогда, чтобы быть уверенным что сработает.

Проблема даже не в CMake, а в целях Makefile.

**Comment by boral660** [comment]
Поправил

**Comment by mamontov-cpp** [comment]
Не исправлено. Среди работ попалась работа, в которой был файл /Лабораторная 1 1/val_example/examplevalidator.cpp, и компилятор не смог его собрать.

**Comment by boral660** [comment]
Исправил

**Comment by mamontov-cpp** [comment]
Ок, проверю завтра.

**Comment by mamontov-cpp** [comment]
Не исправлено по-прежнему: 
  Cannot find source file:



    ../пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ 1/val_example/examplevalidator.cpp

**Comment by boral660** [comment]
Не понимаю, может какая-то проблема с кодировкой?
Лабораторная 1\Лабораторная 1.1\val_example.cpp
Вот такая структура становится такой:
Laboratornaya 1\Laboratornaya 1.1\val_example\examplevalidator.cpp
И никакой ошибки не пишет.
Как будет возможность не могли бы вы посмотреть CMakeList, в папке /buildTemp (там организовал хранение временных файлов)?

**Comment by mamontov-cpp** [comment]
Странно, у меня эта папка не появлялась. Вы точно её организовали?

**Comment by mamontov-cpp** [comment]
У меня получилось, что папка не переименовывается. Вы точно после распаковки проходитесь и переименовываете все папки?

**Comment by boral660** [comment]
![image](https://user-images.githubusercontent.com/19644449/39084821-3f1ecf20-4583-11e8-81d3-dfd480029c4a.png)
Допустим вот такая структура. Он рекурсивно переименовал главную папку, (архив), две папки вложенных, и еще по 3 в каждой папке. Файлы так же переименовывает.
Я думаю тут проблема в том, что имя папки в какой-то иной кодировке получает. Вот и не может транслировать нормально, но правда я не знаю как это проверить.
![image](https://user-images.githubusercontent.com/19644449/39084874-294f1352-4584-11e8-8cfe-dbf91a13afd5.png)

**Comment by mamontov-cpp** [comment]
Попробуйте Zip и Rar файлы создавать через WinRar.

И запускать вашу программу из консоли - может это имеет значение?

**Comment by boral660** [comment]
Проверил через консоль, Zip и Rar. Переименовывает.
Можете скинуть архив, с папкой, на которой вылетает, и я протестю его? 
Думаю мне даже не понадобятся файлы с кодом, главное с папками разобраться.

**Comment by mamontov-cpp** [comment]
http://rgho.st/6vWqFvbDS
http://rgho.st/8pjjNZgxN

**Comment by mamontov-cpp** [comment]
Посмотрите эти. Одна из них точно падает при сборке.

**Comment by boral660** [comment]
[Fail] Ошибка во время компиляции: 
In file included from C:\Apache24\htdocs\diplom\answers\Parser testovyy kurs\21\TesterAleksey TesterBorzyh\Laboratornaya 1\val_example\examplevalidator.cpp:1:0: 
C:\Apache24\htdocs\diplom\answers\Parser testovyy kurs\21\TesterAleksey TesterBorzyh\Laboratornaya 1\val_example\examplevalidator.h:4:22: fatal error: QValidator: No such file or directory 

Переименовывает, но валится на qt сборке. (и первый и второй архив). С qt проблема ясна, я работаю над этим как мы и говорили.
Не ясно тогда, почему у вас не переименовывает. Так же не ясно почему не удаляет папки у вас иногда. Может старая версия, и нужно сделать пулл?

**Comment by mamontov-cpp** [comment]
pull делал. А ОС у вас какая?
Я тестировал на 8.1

**Comment by boral660** [comment]
7. На чем это может сказаться?

**Comment by mamontov-cpp** [comment]
Есть подозрения, что проблема в правах, но вообще пока как-то неясно выходит - почему вы не проверяете результат unlink, rmdir и не делаете связанный с этим вывод?
Это бы позволило бы отладить ситуацию и не гадать в чем дело.

**Comment by boral660** [comment]
![image](https://user-images.githubusercontent.com/19644449/39085524-647af380-458c-11e8-96e2-5229c2522dd4.png)
Проверять результат... Разве этого не достаточно? 

UPD. Нашел место где без проверки, щас доправлю.

**Comment by mamontov-cpp** [comment]
Не совсем достаточно - по идее, лучше помимо этого сообщить ошибку OS, может так?
https://stackoverflow.com/questions/16904440/how-to-access-errno-in-php ?

**Comment by boral660** [comment]
error_get_last() - собственно в точности повторяет всплывающее предупреждение.

**Comment by mamontov-cpp** [comment]
Ок, тогда оставим только обычную проверку.
