### ISSUE TITLE
Проверка протоколов

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#14]
Нужно сделать, чтобы программа желательно проверяла, что в разделе "Протокол"  загружен протокол студента. И, соответственно, отправляла об этом сообщение.

**Comment by boral660** [comment]
Конкретнее, о каком разделе вы говорите?
На мудл можно расширения указывать, но почему-то на .org они просто как напоминанием служат, не ограничивая при этом возможность закидывать файлы других расширений. Вроде бы на edu.vstu.ru там корректно работает, и соответственно проверять расширения файла смысл отпадает.
И об отправке какого сообщения конкретно идет речь?

**Comment by mamontov-cpp** [comment]
Это не к модулю POAS Assignment, скорее к заданию на загрузку файлов (mod_assign).

Пример: http://edu.vstu.org/mod/assign/view.php?id=25

Отправка сообщения - имелся ввиду список того, какие протоколы были загружены студентом, а какие - нет.

**Comment by boral660** [comment]
А разве связаны протокол и конкретные задачи? Они считаются как отдельная задача, с определенным id. Преподаватель так же должен вводить id,  а я буду просто сообщать у кого необходимо проверить загруженный протокол?
И вы еще упоминали о том, что следует ставить оценку за "некомпилируемый код" и упомянули, что "Аналогичное нужно сделать для протоколов". Какие критерии неудачной загрузки протоколов?
Могу проверять расширения, или архив распаковывать, но это всё в самом мудл можно контролировать.

**Comment by mamontov-cpp** [comment]
Критерий один - протокол не загружен. Мы уже говорили с вами - что протокол это отдельный модуль и оценка за него ставится там же.

Даже пример на edu.vstu.org есть.

**Comment by boral660** [comment]
Готово, кроме оценки для протокола (другое ищью)

**Comment by mamontov-cpp** [comment]
Пока закрываю, вроде бы всё ок.
