### ISSUE TITLE
Использовать в отчетах оригинальные имена студентов на русском языке

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#15]
У вас там транслит, но копировать данные в таблицы из-за этого не удобно. Поправьте, пожалуйста.

**Comment by boral660** [comment]
Поправил за одно и в названии курса, и в названии задания

**Comment by mamontov-cpp** [comment]
Отлично, постараюсь проверить.

**Comment by mamontov-cpp** [comment]
Закрываю, сделано
