### ISSUE TITLE
Унификация сообщения об ошибках

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#16]
Если *.cpp файлы  не загружены ли не найдены - ошибка выводится на русском, а остальные на английском.
Приведите их к одному языку

Лучше предварять сообщения префиксом: [FAIL] или [PASS].

**Comment by boral660** [comment]
Привел к единому языку

**Comment by mamontov-cpp** [comment]
Не исправлено в master по-прежнему.

**Comment by mamontov-cpp** [comment]
Пример сообщения: "Тестирование работы по задаче 3207 студента Мария Гребенкина:Error during build on cmake: "

**Comment by boral660** [comment]
Решил всё тогда на русский язык переписать. Fail и Pass следует тоже назвать как "Провалено" "Пройдено" или оставить вот так:
"Тестирование работы по задаче 20 студента ВторойАлексей ВторойБорзых:
[Fail] Ошибка во время компиляции: "

**Comment by mamontov-cpp** [comment]
Второй вариант.

**Comment by boral660** [comment]
Готово

**Comment by mamontov-cpp** [comment]
Серьёзных проблем нет, текущую вынес в отдельное issue.
