### ISSUE TITLE
Кривая логика работы с папками

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#17]
```
PHP Warning:  rmdir(answers/Osnovy programmirovaniya (2-y semestr)/3207/Vladimir
 Artyushin/val_example): Directory not empty in poasassignment-analyzer
\Cleaner.php on line 39
PHP Warning:  rmdir(answers/Osnovy programmirovaniya (2-y semestr)/3207/Vladimir
 Artyushin): Directory not empty in poasassignment-analyzer\Cleaner.php
 on line 39
PHP Warning:  mkdir(): File exists inpoasassignment-analyzer\index.php
 on line 583
PHP Warning:  rmdir(answers/Osnovy programmirovaniya (2-y semestr)/3207/Aleksey
Astankov/lab1): Directory not empty in poasassignment-analyzer\Cleaner.
php on line 39
PHP Warning:  rmdir(answers/Osnovy programmirovaniya (2-y semestr)/3207/Aleksey
Astankov): Directory not empty inpoasassignment-analyzer\Cleaner.php o
n line 39
PHP Warning:  mkdir(): File exists in poasassignment-analyzer\index.php
 on line 583
```

**Comment by boral660** [comment]
Если удалить нет возможности, следует кидать исключение и выходить из скрипта? Варнинги всё равно будут выводится, но по крайней мере не будет продолжаться работа. (Варнинги в последствии можно будет убрать из вывода)

**Comment by mamontov-cpp** [comment]
>PHP Warning:  rmdir(answers/Osnovy programmirovaniya (2-y semestr)/3207/Aleksey
Astankov/lab1): Directory not empty in poasassignment-analyzer\Cleaner.
php on line 39

Вы удаляете папку неверно, нужно сначала удалить из неё файлы, а потом делать rmdir.

**Comment by boral660** [comment]
Так у меня рекурсивно проходит, сначала обходит удаляет все файлы, потом саму папку.
Единственное из-за чего удаление может не произойти, это когда пользователь блочит сам некоторые файлы или папки открывая их, допустим в проводнике. 
Если открыта папка в проводнике, то её не удаляет, и пишет ту ошибку, которую вы показали сверху

**Comment by mamontov-cpp** [comment]
Странно, но папка на тот момент не была открыта в проводнике, вот в чем дело.

**Comment by mamontov-cpp** [comment]
Не похоже, что ситуация исправляется. 
Сегодня на Linux-клиенте получил:
PHP Warning:  rename(answers\Osnovy programmirovaniya (2-y semestr)\3207\Ivan Avdevnin,answers\Osnovy programmirovaniya (2-y semestr)\3207\Ivan Avdevnin) . Может проблема в том, что имена папок совпадают?
Ошибка возникает в index.php 283.

**Comment by mamontov-cpp** [comment]
Проверил, ошибка происходит из-за переименования с тем же именем.

**Comment by mamontov-cpp** [comment]
Пропатчил ошибку в 283 строке:
```
         if ($sdir != $destDirectory) {
             if (!rename($sdir, $destDirectory))
                 throw new Exception('Невозможно переименовать папку: ' . $sdir);
         }
```

Надо поправить Tester.php, с. 358, там не всегда файлы создаются:
```
if (file_exists($path)) {
            $lines = file($path);
        } else {
            $lines = array();
        }
        if (!empty($lines)) {
            array_push($errors, $header_string);
        }
        if (count($lines)) {
            foreach ($lines as $line) {
                if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                    $line = iconv('WINDOWS-1251', 'UTF-8', $line);
                }
                array_push($errors, $line);
            }
        }
```

**Comment by mamontov-cpp** [comment]
Cleaner::removeDirectory кривая, потому что glob/* не возвращает папки, начинающиеся с .

Вот правильная версия:
http://pastebin.ru/NC8o3XLt
Исправьте.

**Comment by mamontov-cpp** [comment]
Неожиданно понял, в чем проблема у вас с транслитерацией. Внимательно посмотрите на код функции \MoodleParser::translitAllFiles . Она у вас транслитерирует только  файлы, когда рекурсивно проходит.

**Comment by mamontov-cpp** [comment]
Ну и сделайте, чтобы была возможность задать версию для консоли. У меня постоянно h3 сыпется в консоль, это не позволяет нормально работать с вашей программой.

**Comment by boral660** [comment]
Насчет трансляции и удаления - вроде подправил.
Пояснение по функции - \MoodleParser::translitAllFiles.
Вначале этой функции идёт рекурсивная трансляция папок(выделена в отдельную функцию), а потом уже и самих файлов.

Реализовал возможность выбора формата результатов для этого следует указать опцию write_on (по умолчанию формируется вывод для консоли). Возможные значения - "browser", "console", "log".

**Comment by mamontov-cpp** [comment]
Я видел, но она почему-то не до конца заходит в папки. Иногда пропускает - причем целую кучу папок.

**Comment by mamontov-cpp** [comment]
Написал в conf.ini  (Linux-конфигурация)
```
send_result_on_email = true
write_on_comment = false
write_on_log = true
write_on = console
email = "mamontov.dp@gmail.com"

[moodle_settings]
login_url = "http://edu.vstu.ru/login/index.php"
task_url = "http://edu.vstu.ru/mod/poasassignment/view.php?id="
task_id[] = 3207

[client_settings]
linux_client = true
cookie_file = "cookie.txt"

save_answers = true
files_download_to = "answers"

unpack_answers = true
path_to_winrar = 'C:\Program Files\WinRAR\WinRAR.exe'

build_and_compile = true
path_to_CMake = 'C:\Program Files\CMake\bin'
generator_for_CMake = "Unix Makefiles"
path_to_QMake = 'C:\Qt2\5.5\mingw492_32\bin'
path_to_Make = 'C:\MinGW\bin'
```

Всё равно получаю в консоли ерунду вида:
```
Авторизация успешна<br>Курс получен<br><h3>Ответ на Задание к лабораторной работе №1 : Ответы   в курсе  Основы программирования (2-й семестр)  предоставили 33 студентов:</h3><p><a href="http://edu.vstu.ru/user/profile.php?id=11453&course=23">Иван Авдевнин</a>
```

Проблема возникает, если выбрасывается в процессе работы исключение.

**Comment by mamontov-cpp** [comment]
У вас ещё воо многих местах используются вместо \ //, которые не работают под линуксом. Есть же DIRECTORY_SEPARATOR - его и используйте.

Пропатчил translitAllDir - теперь всё наконец-то работает: 
http://pastebin.ru/W5xeRIzl

Поправьте комментарий выше (про write_on).

**Comment by boral660** [comment]
Готово

**Comment by mamontov-cpp** [comment]
Закрыл, всё ок.
