### ISSUE TITLE
Снижение оценки за некомпилирируемый код

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#18]
Надо сделать, чтобы ставилась оценка заданная в настройках, за некомпилируемый код.

Аналогичное нужно сделать для протоколов.

Это - по идее последняя задача, после этого программу можно считать готовой, если всё остальное работает.

**Comment by mamontov-cpp** [comment]
По вчерашней консультации нашел неплохой мануал:
https://lornajane.net/posts/2011/posting-json-data-with-php-curl

**Comment by boral660** [comment]
Реализовал

**Comment by mamontov-cpp** [comment]
Ок, закрываю.
