### ISSUE TITLE
Неверная реализация unpackFIle под Linux

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#19]
Сначала не заметил, но потом увидел проблему:
в \MoodleParser::unpackFile для распаковки файлов под Linux используется unrar. И так для всех архивов.  Но это неверно: для zip файлов нужно использовать unzip, а для tar  и tar.gz - tar с определенными ключами. Поставьте уже себе Linux хотя бы на виртуалку и проверьте.

**Comment by boral660** [comment]
Готово

**Comment by mamontov-cpp** [comment]
Отлично, нет замечаний.
