### ISSUE TITLE
Построение тестового проекта с запуском CMake/QMake.

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#2]
До сих пор не реализовано.

**Comment by boral660** [comment]
Для cmake реализовал сборку и компиляцию, правда пока без вывода ошибок.
При работе с QMake столкнулся с проблемой.
В QMake нет опции, позволяющей указать папку в которую будут  сохранятся Makefiles. Т.е. по факту все файлы создаются там, от куда я вызвал qmakе, в данном случае папка со скриптом.
Нашел как через .pro файлы можно указать папку для релиза-дебага, однако makefiles всё равно сохраняются в папке по умолчанию

**Comment by mamontov-cpp** [comment]
Это не так важно, где будут храниться Makefiles. На худой конец - можно стереть их он их пересоздать. Такого задания не было. Зачем вам это нужно?

**Comment by boral660** [comment]
Реализованно
