### ISSUE TITLE
Некорректное сообщение в консоли

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#21]
Тестирование работы по задаче 3207 студента Алексей Шуклин:Array[Fail] Ошибка во                          время компиляции при сборке qt:
/bin/sh: 1: Syntax error: "(" unexpected

Откуда взялся Array?

Почему ( unexpected

Воспроизводится под линуксом.

**Comment by boral660** [comment]
Баг с array исправил, а баг с  "( unexpected" не пойму от куда мог взяться.
Если этот баг только на определенных проектах возникает, перешлите их по возможности мне для тестирования.

**Comment by mamontov-cpp** [comment]
Ок, найду - перешлю. Попробуйте под линем позапускать - мб в этом дело?

**Comment by boral660** [comment]
Линукс у меня стоит, правда mint. Тесты проходят.
Может быть проблема из-за разницы в системах, но я не думаю.

**Comment by mamontov-cpp** [comment]
http://rgho.st/6GjjXxwDZ

Сам файл. Там реально cpp прикреплён.

**Comment by boral660** [comment]
Так, я проверил этот файл, а так же русские буквы в названии, и пробелы. Собственно ошибка не появляется.
Ошибка может появится, если не поставить опцию "linux_client", и при этом в path_to_QMake установить некорректный путь.

**Comment by mamontov-cpp** [comment]
Погодите-ка а зачем в linux_client учитывать path_to_QMake? По идее там и простого вызова qmake достаточно?

**Comment by boral660** [comment]
Если опция "linux_client" установлена, то путь не требуется. Но если по какой-то причине её не установили, то программа считает, что система виндовс и обращается по path_to_QMake.
В теории, можно убрать это свойство и везде проверять ос программно

**Comment by mamontov-cpp** [comment]
Нет, установил его  в /usr/bin, linux_client установлен в true, ситуацию не поправило.

В порядке бреда: а добавьте скобки в название курса, который парсится. Может они влияют?

**Comment by boral660** [comment]
Точно, проблема в скобках. А точнее в работе make со скобками.
Может их просто вырезать при создании папок? Вообще желательно вырезать все символы которые требуют написания в ковычках
https://lists.debian.org/debian-qt-kde/2014/03/msg00030.html

**Comment by mamontov-cpp** [comment]
Ок, заменяйте на подчеркивания.

**Comment by boral660** [comment]
Выполнил

**Comment by mamontov-cpp** [comment]
Отлично, работает.
