### ISSUE TITLE
Опции хранения списка проверенных работ между состояниями и проверка только изменённых

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#22]
Необходимо сделать опцию, при которой программа бы хранила timestamp времени проверки каждого из заданий и делала бы изменения и повторную проверку только если файлы изменились

**Comment by boral660** [comment]
Не до конца понимаю как это реализовать.
Допустим я создам некоторый json файл, хранящий время проверки каждого из ответов студентов (как я понял, вы именно это имели ввиду).
Но как мне понять изменились файлы, или нет?
Можно с Moodle получить дату последней загрузки работы в moodle, и хранить именно её. Тогда если в файле дата старше, чем при новой проверке, следует протестировать эту работу.

**Comment by mamontov-cpp** [comment]
Думаю, что последний ваш вариант подойдёт лучше.

**Comment by boral660** [comment]
Выполнил.
Опция для подключения данной возможности "check_only_new_work".

**Comment by mamontov-cpp** [comment]
Ок, проверю вечером.

**Comment by mamontov-cpp** [comment]
file_get_contents(TestingTime.json): failed to open stream - ну и зачем он туда лезет если опция не установлена?

**Comment by mamontov-cpp** [comment]
И если это нужно - почему не проверить через file_exists?

**Comment by boral660** [comment]
Поправил

**Comment by mamontov-cpp** [comment]
Закрываю, работает.
