### ISSUE TITLE
Форматирование и рефакторинг проекта

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#3]
1) Форматирование в https://github.com/boral660/poasassignment-analyzer/blob/master/indexOriginal.php довольно плохое, нужно провести его рефакторинг и привести хотя бы к PSR1, PSR2
2) Почему здесь всего один класс MoodleParser, который отвечает за всё? 
По-хорошему надо разбить это всё на несколько классов, которые будут отвечать за парсинг, компиляцию, отправку сообщений
3) Почему e-mail захардкожен?, см. 524 строку

**Comment by mamontov-cpp** [comment]
4. По-хорошему надо сделать список того софта, который нужен для работы вашей программы.

**Comment by boral660** [comment]
1. Провёл рефакторинг в соответствии со стандартом PSR2
2. Разбил код на 3 класса, в дальнейшем еще будет класс для отправки сообщения и написания комментария в moodle
3. Старая версия была, метод был некорректно реализован. Реализация в процессе
4. Необходимые утилиты для работы расписал в readme

**Comment by mamontov-cpp** [comment]
build_and_compil  - какая-то опечатка в названии.

**Comment by mamontov-cpp** [comment]
indexOriginal.php можно переименовать в index.php?

**Comment by boral660** [comment]
Исправил недочеты.
