### ISSUE TITLE
Сообщение об ошибках в комментарии 

### ISSUE THREAD

**Issue by boral660** [boral660/poasassignment-analyzer#4]
Пользователю необходимо отправлять сообщение об ошибках возникших при компиляции.
Следует ли сообщать пользователю о проблемах с архивом? (невозможно распаковать)
Главная проблема то, что достаточно тяжело отличить ошибки системные от ошибок возникших именно с работой студента. Как их отличить, если я по сути получаю всё из одного потока ошибок? 
Не хотелось бы сообщать студенту об ошибках при работе скрипта. Как я понимаю, следует четко забить в код основные ошибки, которые могут возникнуть с программами, и, если они возникли, не отправлять комментарий для студента.

**Comment by mamontov-cpp** [comment]
Бог с ними, постите все, если знаете какие-то системные - отфильтруйте.

**Comment by boral660** [comment]
Возникли некоторые проблемы, с попыткой заполнить форму для комментария через culr_post в связи со специфичностью сохранения (отдельной ссылкой) комментария. 

![image](https://user-images.githubusercontent.com/19644449/38576798-d75db582-3d07-11e8-8b81-b06a3a17e453.png)

**Comment by mamontov-cpp** [comment]
По-хорошему придётся имитировать AJAX-запрос на этой странице.
Как получить адрес и структуру на вкладке Network хрома знаете?

**Comment by boral660** [comment]
Нет, впервые с этим сталкиваюсь. Буду разбираться

**Comment by mamontov-cpp** [comment]
Перед работой на странице в браузере ПКМ на странице, выбираете "Посмотреть код". Потом переключаетесь на вкладку Network. Потом начинаете добавлять комментарий и в таблице должна появиться строка с запросом.

**Comment by boral660** [comment]
Реализовал

**Comment by mamontov-cpp** [comment]
Ок, закройте (я не owner, закрыть не могу).
