### ISSUE TITLE
Проблемы с парсингом UTF-8 файлов на сервере

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#5]
У нас на сервере edu.vstu.ru вроде как страница  отдаётся в UTF-8.
Из-за этого парсер сходит с ума: создаёт папки с именами вида
РћСЃРЅРѕРІС‹ РїСЂРѕРіСЂР°РјРјРёСЂРѕРІР°РЅРёСЏ (2-Р№ СЃРµРјРµСЃС‚СЂ)
И падает при попытке работать с ними.
Соответственно на этом падает CMake и прочее.

**Comment by boral660** [comment]
А как мне это протестировать? Чисто примерно я могу написать код, но без доступа к сайту это будет как работа в слепую.

**Comment by mamontov-cpp** [comment]
Просто добавьте конвертирование кодировки в строках в нативную, т.к. у вас нативная UTF-8 строка используется для сохранения файла. Это нужно только для винды, в остальных случаях это будет ок.

**Comment by boral660** [comment]
Разобрался в чём проблема. Одна из программ не хочет работать с файлами, у которых в пути кириллица. (Смена кодировки не помогла), пришлось всё переводить в транслит. Должно работать

**Comment by mamontov-cpp** [comment]
Работает, ок. Закрываю.
