### ISSUE TITLE
Логгирование работы программы

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#6]
Нужно сделать, чтобы логи программы сохранялись в файл, а то curl и компания на скачке курса выдают целую гору логов , их нельзя нормально прочитать.

**Comment by mamontov-cpp** [comment]
Скорее, нужно перехватить ещё поток ошибок, т.к. большая часть логов идёт оттуда.

**Comment by boral660** [comment]
Вопрос, сохранять лог программы в формате html (как собственно и заполняется на экране), или нужно будет при логировании от всех тэгов избавляться?
И наверное насчёт отправки на почту, лучше файл же кидать, чем html страничку?

**Comment by mamontov-cpp** [comment]
Лучше файл, лог программы можно в обычном *.log хранить

**Comment by boral660** [comment]
Сейчас у меня всё что на экране прописывается, записывается в файл логов. 
Далее нужно создать еще один файл с логами, который будет ловить ошибки curl? Это обязательно?

**Comment by mamontov-cpp** [comment]
Нет, достаточно общего файла логов.

**Comment by boral660** [comment]
Реализовал

**Comment by mamontov-cpp** [comment]
Где реализовал? Не вижу, чтобы была настройка общего файла логов, Не вижу, чтобы он писался.

**Comment by mamontov-cpp** [comment]
Логи появились в папке Logs. Что нужно сделать, так это убрать curl из вывода в консоли + описать это в README. Пока вообще не было ясно что происходит.

**Comment by boral660** [comment]
Добавил опцию позволяющую весь результат записать в лог.
Перенаправил поток с курл в отдельный лог файл.
Поправил реадми.

**Comment by mamontov-cpp** [comment]
Закрываю, всё хорошо здесь.
