### ISSUE TITLE
Некорректный селектор не подходит для edu.vstu.ru (index.php, с. 245)

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#7]
PHP выдаёт 
PHP Notice:  Trying to get property of non-object in D:\saddy\poasassignment-analyzer\index.php on line 245

Это из-за того, что производится попытка поиска по селектору
//*[@id="region-main"]/div/div/h2/text()
Но на edu.vstu.ru второго div'а нет.

Можно ли сделать так, чтобы поиск делался по id, а потом в нём просто искался h2 на любом уровне вложенности?

**Comment by boral660** [comment]
Исправил. Вроде бы.

**Comment by mamontov-cpp** [comment]
Ок, вечером проверю.

**Comment by mamontov-cpp** [comment]
Работает, закрываю
