### ISSUE TITLE
Почему-то компилятор ищется по пути в CMake

### ISSUE THREAD

**Issue by mamontov-cpp** [boral660/poasassignment-analyzer#8]
У меня его там нет, но утилита почему-то ищет make.exe там где находится CMake. Нужно дать CMake самому выбрать компилятор.

Для g++ он вполне может сам вывести расположение make.exe.
Максимум - хорошо бы в конфиг добавить выбор генератора для CMake

**Comment by boral660** [comment]
Компилятор у меня ищется только потому, что у меня там он и лежит. Можно указать в конфигурации другой путь для него.
Добавил возможность выбора генератора для cmake

**Comment by mamontov-cpp** [comment]
Да нет, разделите пути к компилятору и путь к CMake - сделайте две разные опции.

**Comment by boral660** [comment]
![image](https://user-images.githubusercontent.com/19644449/38771485-afe2d17c-402c-11e8-930a-c45319537ba8.png)
Ну что вы имеете ввиду под компилятором? На make опция с самого начала стояла.
А путь к MinGW нужно заносить в переменные среды, что бы cmake их видел. Конкретные пути в парсере нигде не указываются (если это вообще возможно, я этого не нашёл).

**Comment by mamontov-cpp** [comment]
Странно, пути к Make там нам не было. А почему вы дергаете по Windows make, если корректный вариант - mingw32-make?

**Comment by mamontov-cpp** [comment]
Кстати, в mingw-w64 нет make.exe. До сих пор не сделано, чтобы дергался mingw32-make для MinGW. Сделайте, пожалуйста.

**Comment by boral660** [comment]
Реализовал, теперь для windows нужно указывать путь к папке с mingw32-make.exe

**Comment by mamontov-cpp** [comment]
Отлично! Завтра протестирую.

**Comment by mamontov-cpp** [comment]
Закрываю, всё заработало.
